services:
  webapi:
    volumes:
      - ./bin/Debug/net8.0:/app/bin/Debug/net8.0
    image: chatflowwebapi
    container_name: chatflowwebapi
    build:
      context: .
      dockerfile: ./Presentation/ChatFlow.WebAPI/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ChatFlowDatabase=Host=db;Database=chatflowDB;Username=postgres;Password=khayal
    depends_on:
      - db
    networks:
      - chatflow

  db:
    image: postgres:latest
    container_name: chatflowdb
    environment:
      POSTGRES_DB: chatflowDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khayal
    volumes:
      - chatflow-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chatflow

  mvc:
    volumes:
      - ./bin/Debug/net8.0:/app/bin/Debug/net8.0
    image: chatflowmvc
    container_name: chatflowmvc
    build:
      context: .
      dockerfile: ./Presentation/ChatFlow.Mvc/Dockerfile
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ChatFlowDatabase=Host=db;Database=chatflowDB;Username=postgres;Password=khayal
    depends_on:
      - webapi
      - db
    networks:
      - chatflow

networks:
  chatflow:
   driver: bridge


volumes:
  chatflow-db-data: